config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get '/home/about', to: 'home#about'
  get '/users/:id/following', to: 'users#following'
  get '/users/:id/followers', to: 'users#followers'
  get '/search', to: 'search#search'

  resources :notifications, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
  end
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :index, :create, :edit, :update, :show] do
    resources :comments, only: [:create, :destroy]
    resources :teams, only: [:new, :index, :create, :edit, :update, :show], shallow: true
    resources :participations, shallow: true
    resources :games, only: [:new, :index, :create, :edit, :update, :show] do
      collection do
        get 'halfway'
        post 'halfway'
        get 'battles'
        post 'battles'
      end
    end
  end

  resources :locations, only: [:new, :index, :create, :edit, :update, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  # presence: { message: "が入力されていません。"},
  # length: { maximum: 15, minimum: 1, message: "は1文字以上15文字以内です。"}
  validates :email, uniqueness: { case_sensitive: false }, presence: true

  has_many :events, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :resolutes, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  # フォローされているユーザを取り出す
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  mount_uploader :image, ImagesUploader

  # フォローしているか確認するメソッド
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  # フォローするメソッド
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  # フォローの通知機能
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "devise/registrations/new" 
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  password = Devise.friendly_token.first(7)
  if session[:provider].present? && session[:uid].present?
    @user = User.create(name:session[:name], email: session[:email], password: password, password_confirmation: password)
    sns = SnsCredential.create(user_id: @user.id,uid: session[:uid], provider: session[:provider])
    binding.pry
  else
    @user = User.create(name:session[:name], email: session[:email], password: session[:password], password_confirmation: session[:password_confirmation])
    binding.pry
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    participations = Participation.where('user_id=?', @user.id)
    @events = Event.where(id: participations.map { |t| t.event_id }).order(start_date: "ASC")
    @user_relation = current_user

    # <start> 会員の勝利数を取得する処理
    @resolutes = Resolute.where(user_id: @user.id)                      # 参加した試合情報を取得する  ※ @resolutes.countで参加した試合数が取得できる
    game_ids = []                                                       # 会員が参加した試合のidを取得するため空の配列を定義
    @resolutes.each do |resolute|                                       # 参加した試合のidから試合idのみ取得する
      game_ids.push(resolute.game_id.to_i)
    end

    @games = Game.where(id: game_ids)                                   # 取得した試合idから試合結果情報を取得する
    win_ids = []                                                        # 試合結果情報から勝利したチームのidを取得するため空の配列を定義
    @games.each do |game|                                               # 取得した試合結果情報から勝利したチームのidを取得する
      win_ids.push(game.win_id.to_i)
    end    

    # where関数にて重複したデータを削除してしまっている
    team_details = []
    win_ids.each do |win_id|
      team_detail = TeamDetail.where(team_id: win_id)
      team_details.push(team_detail)              # 取得した勝利チームのidからそのチームに所属していたチーム詳細情報を取得する
    end    
    # team_details = TeamDetail.where(team_id: win_ids)                 # 取得した勝利チームのidからそのチームに所属していたチーム詳細情報を取得する
    participation_ids = []                                              # チーム詳細情報から勝利したチームに所属していた参加者のidを取得するため空の配列を定義
    team_details.flatten.each do |team_detail|                                  # 取得した参加者情報から参加者idを取得する
      participation_ids.push(team_detail.participation_id.to_i)
    end        

    count = 0
    participation_ids.each do |participation_id|
      if Participation.find_by("id=? and user_id=?", participation_id, @user.id) != nil
        count += 1        
      end
    end
    @win_count = count    

    # <finish> 会員の勝利数を取得する処理

    # <start> チャット機能
    @current_user_room = UserRoom.where(user_id: current_user.id)
    @user_user_room = UserRoom.where(user_id: @user.id)
    if @user.id != current_user.id
      @current_user_room.each do |current_user|
        @user_user_room.each do |user|
          if current_user.room_id == user.room_id
            @isRoom = true
            @roomId = user.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @user_room = UserRoom.new
      end
    end
    # <finish> チャット機能
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings                 # followingsメソッドはuserモデルに記述してある
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers                  # followersメソッドはuserモデルに記述してある
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_k, :image, :introduction, :email, :age, :phone_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_calendar.html.erb
<div class="calendar">
  <div class="text-center">
    <%= month_calendar events: @events do |date, events| %>
      <%= date %>

      <% events.each do |event| %>
        <div>
          <%= link_to "#{event.event_name}", event_path(event) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_chat.html.erb
          <% if (current_user.following? @user) && (@user.following? current_user)  %>
            <% if @isRoom == true %>
              <div class="row">
                <p class="user-show-room">
                <a href="/rooms/<%= @roomId %>" class="btn btn-primary" width=300>チャットへ</a>
              </div>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @user_room do |user| %>
                  <%= user.hidden_field :user_id, value: @user.id %>
                <% end %>
                  <div class="row" width=300>
                    <%= f.submit "チャットを始める", class:"btn btn-primary user-show-chat" %>
                  </div>
              <% end %>
            <% end %>
          <% end %>

app/views/users/_event_index.html.erb
      <div class="index-event__panel panel panel-success">
        <div class="index-event__panel__heading panel-heading">
          <h3>イベント一覧</h3>
        </div>
        <div class="index-event__panel__body panel-body">
          <h4>参加しているイベントです。</h4>
            <ul>
              <% @events.each do |event| %>
                <% if event.finish_date > Time.zone.now %>
                  <li><%=link_to "#{event.event_name}", event_path(event), class: "index-item__event__panel__body__link" %></li>
                <% end %>
              <% end %>
            </ul>
        </div>
      </div>

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn col-xs-12" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'users/unfollow' %>
    <% else %>
      <%= render 'users/follow' %>
    <% end %>
  </div>
<% end %>  

app/views/users/_index.html.erb
<div class="index">
  <div class="row">
    <div class="index-event col-lg-6 col-md-12">

      <%= render 'event_index' %>

    </div>
    <div class="index-game col-lg-6 col-md-12">

      <%= render 'game_index' %>

    </div>
  </div>
</div>

app/views/users/_introduction.html.erb
<div class="introduction">
  <div class="row introduction__header">
    <div class="introduction__header__image text-center col-md-12 col-lg-4">
      <% if @user.image? %>
        <%= image_tag(@user.image.to_s, size: "250x250") unless @user.image.file.nil? %>
      <% else %>
        <%= image_tag("no_image.jpg", size: "250x250") %>
      <% end %>
    </div>
    <div class="introduction__header__text text-center col-md-12 col-lg-8">
      <div class="introduction__header__text__top row">
        <div class="introduction__header__text__top__name text-center col-xs-5">
          <%= @user.name %>
        </div>
        <% if @user.id == current_user.id %>
          <%= link_to edit_user_path(@user), class: "btn btn-default introduction__header__text__top__edit text-center col-xs-offset-2 col-xs-3 edit_user_#{@user.id}" do %>
            <span style="font-size: 1em;">
              <i class="fas fa-user-cog"></i>
            </span>
          <% end %>
        <% else %>
          <% unless current_user?(@user) %>
            <div id="follow_form">
              <% if current_user.following?(@user) %>
                <%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "フォローを外す", class: "btn btn-large btn-primary follow-btn" %>
                <% end %>
              <% else %>
                <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
                  <div><%= f.hidden_field :following_id %></div>
                  <%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn" %>
                <% end %>
              <% end %>
            </div>
          <% end %>
          
          <%= render "chat" %>
          
        <% end %>
      </div>
      <div class="row user_follow">
        <div class="col-xs-4">フォロー<%= link_to @user.followings.count, following_user_path(@user) %>人</div>
        <div class="col-xs-4">フォロワー<%= link_to @user.followers.count, followers_user_path(@user) %>人</div>
      </div>
      <div class="row game_resolute">
        <div class="col-lg-3 col-md-6 col-xs-6 game_resolute__item">
          <% if @resolutes.count == 0 || @win_count == 0 %>
            勝率：0％
          <% else %>
            勝率：<%= "#{(((@win_count.to_f) / (@resolutes.count.to_f)) * 100).round(1)}％" %>
          <% end %>
        </div>
        <div class="col-lg-3 col-md-6 col-xs-6 game_resolute__item">試合数：<%= "#{@resolutes.count}回" %></div>
        <div class="col-lg-3 col-md-6 col-xs-6 game_resolute__item">勝ち数：<%= "#{@win_count}回" %></div>
        <div class="col-lg-3 col-md-6 col-xs-6 game_resolute__item">負け数：<%= "#{@resolutes.count-@win_count}回"  %></div>
      </div>
    </div>
  </div>
  <div class="introduction__header__text__introduce text-center">
    <%= @user.introduction %>
  </div>
</div>

app/views/users/_past.html.erb
<div class="index">
  <div class="row">
    <div class="index-event col-lg-6 col-md-12">
      <div class="index-event__panel panel panel-success">
        <div class="index-event__panel__heading panel-heading">
          <h3>過去イベント一覧</h3>
        </div>
        <div class="index-event__panel__body panel-body">
          <h4>過去に参加イベントです。</h4>
            <ul>
              <% @events.each do |event| %>
                <% if event.finish_date < Time.zone.now %>
                  <li><%=link_to "#{event.event_name}", event_path(event), class: "index-item__event__panel__body__link" %></li>
                <% end %>
              <% end %>
            </ul>
        </div>
      </div>

    </div>
    <div class="index-game col-lg-6 col-md-12">

    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを外す", class: "btn btn-large btn-primary follow-btn col-xs-12" %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>

  <h2><%= @user.errors.count %>errors prohibited this  from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="user-edit">
  <div class="bottom-color">登録情報編集</div>
  <div class="user-edit__container">
    <%= form_for @user do |f| %>

      <div class="user-edit__container__label">
        <%= f.label :name, "名前", class: "" %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
      </div>

      <div class="user-edit__container__label">
        <%= f.label :name_k, "ナマエ", class: "" %>
        <%= f.text_field :name_k, autofocus: true, autocomplete: "name_k", class: "form-control" %>
      </div>

      <div class="user-edit__container__label">
        <%= f.label :image, "プロフィール写真" %><br>
        <%= f.file_field :image, class: "form-control" %><br>
      </div>

      <div class="user-edit__container__label">
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>
    
      <div class="user-edit__container__label">
        <%= f.label :age, "年齢" %>
        <%= f.number_field :age, autofocus: true, autocomplete: "age", class: "form-control" %>
      </div>

      <div class="user-edit__container__label">
        <%= f.label :phone_number, "電話番号" %>
        <em>(ハイフンなし)</em>
        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class: "form-control" %>
      </div>

      <%= f.submit "編集内容を保存する", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <h2>Follower Users</h2>

  <table class="table">
    <thead>
      <tr>
        <th>名前</th>
        <th>歳</th>
        <th>紹介文</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.age %></td>
          <td><%= user.introduction %></td>
          <td>
            フォロー数：<%= user.followings.count %>
          </td>
          <td>
            フォロワー数：<%= user.followers.count %>
          </td>
          <td>
            <% unless current_user?(user) %>
              <div id="follow_form">
              <% if current_user.following?(user) %>
                <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "フォローを外す", class: "btn btn-large btn-primary follow-btn" %>
                <% end %>
              <% else %>
                <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
                  <div><%= f.hidden_field :following_id %></div>
                  <%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn" %>
                <% end %>
              <% end %>
              </div>
            <% end %>  
          </td>
          <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/following.html.erb
<div class="container">
  <h2>Follow Users</h2>

    <table class="table">
      <thead>
        <tr>
          <th>名前</th>
          <th>歳</th>
          <th>紹介文</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.age %></td>
          <td><%= user.introduction %></td>
          <td>
            フォロー数：<%= user.followings.count %>
          </td>
          <td>
            フォロワー数：<%= user.followers.count %>
          </td>
          <td>
            <% unless current_user?(user) %>
              <div id="follow_form">
              <% if current_user.following?(user) %>
                <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "フォローを外す", class: "btn btn-large btn-primary follow-btn" %>
                <% end %>
              <% else %>
                <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
                  <div><%= f.hidden_field :following_id %></div>
                  <%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn" %>
                <% end %>
              <% end %>
              </div>
            <% end %>  
          </td>
          <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/index.html.erb
	<div>
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>名前</th>
					<th>歳</th>
					<th>紹介文</th>
					<th colspan="2"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= user.name %></td>
						<td><%= "#{user.age}歳" %></td>
						<td><%= user.introduction %></td>
						<td>
							フォロー数：<%= link_to user.followings.count, following_user_path(@user) %>
						</td>
						<td>
							フォロワー数：<%= link_to user.followers.count, followers_user_path(@user) %>
						</td>
						<td>
							<% unless current_user?(user) %>
								<div id="follow_form">
									<% if current_user.following?(user) %>
										<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
											<%= f.submit "フォローを外す", class: "btn btn-large btn-primary follow-btn" %>
										<% end %>
									<% else %>
										<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
											<div><%= f.hidden_field :following_id %></div>
											<%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn" %>
										<% end %>
									<% end %>
								</div>
							<% end %>  
						</td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>

app/views/users/show.html.erb
<div class="user-show">
  
  <%= render 'introduction' %>

  <%= render 'calendar'%>

  <%= render 'index' %>

  <%= render 'past' %>

</div>