config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get '/home/about', to: 'home#about'
  get '/users/:id/following', to: 'users#following'
  get '/users/:id/followers', to: 'users#followers'
  get '/search', to: 'search#search'

  resources :notifications, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
  end
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :index, :create, :edit, :update, :show] do
    resources :comments, only: [:create, :destroy]
    resources :teams, only: [:new, :index, :create, :edit, :update, :show], shallow: true
    resources :participations, shallow: true
    resources :games, only: [:new, :index, :create, :edit, :update, :show] do
      collection do
        get 'halfway'
        post 'halfway'
        get 'battles'
        post 'battles'
      end
    end
  end

  resources :locations, only: [:new, :index, :create, :edit, :update, :show]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :participations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :event_types, dependent: :destroy
  has_many :types, through: :event_types
  
  # 通知機能
  has_many :notifications, dependent: :destroy

  mount_uploader :image, ImagesUploader

  validates :type_id, presence: true
  validates :event_name, presence: true
  validates :introduction, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :place_name, presence: true
  validates :address, presence: true

  def start_time
    start_date
  end

  # コメントの通知機能
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(event_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      event_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/event_type.rb
class EventType < ApplicationRecord
  belongs_to :event
  belongs_to :type
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def new
    @event = Event.new
  end

  def index
    if params[:type_id].present?
      @events = Event.where(type_id: params[:type_id]).order(start_date: "ASC")
    else
      @events = Event.all.order(start_date: "ASC")
    end
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.save
    Participation.create!(
      event_id: @event.id,
      user_id: current_user.id,
      status: "参加",
    )
    redirect_to event_path(@event)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
    @participations = Participation.where('event_id=? and status=?', params[:id], "参加")
    @participation = Participation.find_by('event_id=? and user_id=?', params[:id], current_user.id)
    @participationnew = Participation.new
    @comment = Comment.new
    @comments = @event.comments
  end

  private

  def event_params
    params.require(:event).permit(:type_id, :event_name, :introduction, :start_date, :finish_date, :place_name, :address)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_comment.html.erb
	<div class="text-center participation-action">
    <% if @participation == nil %>
      <%= link_to "このイベントに参加する", event_participations_path(event_id: params[:id]), method: :post, status: "参加", class: "btn btn-lg btn-success" %>
    <% else %>
      <% if @event.finish_date > Time.zone.now %>
        <% if @event.start_date < Time.zone.now %>
          <%= link_to "試合を始める", new_event_game_path(event_id: params[:id]), class: "btn btn-lg btn-success" %>  
        <% end %>
        <%= link_to "参加を取りやめる", participation_path(event_id: params[:id], user_id: current_user.id), method: :delete, class: "btn btn-lg btn-danger" %>
      <% else %>
        <%= link_to "試合結果を見る", event_games_path(event_id: params[:id]), class: "btn btn-lg btn-success" %>
      <% end %>
    <% end %>
	</div>
  <div class="comment-container">
    <h2>コメント一覧</h2>
    <div id="comments_area" class="comment-area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
    </div>

    <% if user_signed_in? %>
      <%= render partial: 'comments/form', locals: { comment: @comment, event: @event } %>
    <% end %>
  </div>

app/views/events/_event_show_top.html.erb
  <div class="event-show-top">
    <div class="event-show-top__container">
      <div class="event-show-top__container__item">
        <div class="bottom-color"><%= @event.event_name %></div>
        <% if @event.user_id == current_user.id %>
          <div class="event-edit">
            <%= link_to edit_event_path do %>
              <i class="fas fa-cog icon-orange"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="map-area">
      <div id="map" class="<%= @event.address %>"></div>
      <div class="map-area__address text-center">
        <h3>住所</h3>
        <p><%= @event.address %></p>
        <p><%= "施設名：#{@event.place_name}" %></p>
      </div>
    </div>
    <div class="row event-show-top__details">
      <div class="col-md-6 col-sm-12 event-show-top__details__type text-center">
        <p>種目：<span><%= Type.find_by(id: @event.type_id).name %></span></p>
      </div>

      <div class="col-md-6 col-sm-12 event-show-top__details__date text-center">
        <p>開催日時：<span><%= @event.start_date.strftime('%Y年%m月%d日 %H:%M') %></span></p>
        <p>終了日時：<span><%= @event.finish_date.strftime('%Y年%m月%d日 %H:%M') %></span></p>
      </div>
    </div>
  </div>

app/views/events/_map.html.erb
<%# <div id="map-container"></div> %>


<%# <script src="//code.jquery.com/jquery-1.12.0.min.js"></script> %>
<%#= javascript_include_tag 'jquery.japan-map.min.js' %>
<%# <script>
  $(function(){        
    var areas = [
      {code : 1, name: "北海道地方", color: "#7f7eda", hoverColor: "#b3b2ee", prefectures: [1]},
      {code : 2, name: "東北地方",   color: "#759ef4", hoverColor: "#98b9ff", prefectures: [2,3,4,5,6,7]},
      {code : 3, name: "関東地方",   color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [8,9,10,11,12,13,14]},
      {code : 4, name: "中部地方",   color: "#7cdc92", hoverColor: "#aceebb", prefectures: [15,16,17,18,19,20,21,22,23]},
      {code : 5, name: "近畿地方",   color: "#ffe966", hoverColor: "#fff19c", prefectures: [24,25,26,27,28,29,30]},
      {code : 6, name: "中国地方",   color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [31,32,33,34,35]},
      {code : 7, name: "四国地方",   color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [36,37,38,39]},
      {code : 8, name: "九州地方",   color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [40,41,42,43,44,45,46]},
      {code : 9, name: "沖縄地方",   color: "#eb98ff", hoverColor: "#f5c9ff", prefectures: [47]},
    ];

    $("#map-container").japanMap({
      width: 800,
      // selection: "area",
      selection: "prefecture",
      areas: areas,
      backgroundColor : "#f2fcff",
      borderLineColor: "#f2fcff",
      borderLineWidth : 0.25,
      lineColor : "#a0a0a0",
      lineWidth: 1,
      drawsBoxLine: true,
      showsPrefectureName: true,
      prefectureNameType: "short",
      movesIslands : true,
      fontSize : 11,
      onSelect : function(data){
        // $.ajax(url: '/events', type: "GET", data:{prefecture: data.name});

      alert(data.name);
      }
    });
  });
</script> %>

app/views/events/_mapstyle.html.erb
<script>
  let map
  let geocoder

  function initMap(){
    // geocoderを初期化
    geocoder = new google.maps.Geocoder()
    geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
      if (status == 'OK') {
        // map.setCenterで地図が移動
        map.setCenter(results[0].geometry.location);

        // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });

    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.681236, lng: 139.767125},
    zoom: 15,
    styles:
          [
          {
              "featureType": "all",
              "elementType": "labels",
              "stylers": [
                  {
                      "visibility": "on"
                  }
              ]
          },
          {
              "featureType": "all",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "saturation": 36
                  },
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 40
                  }
              ]
          },
          {
              "featureType": "all",
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "visibility": "on"
                  },
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 16
                  }
              ]
          },
          {
              "featureType": "all",
              "elementType": "labels.icon",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "featureType": "administrative",
              "elementType": "geometry.fill",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 20
                  }
              ]
          },
          {
              "featureType": "administrative",
              "elementType": "geometry.stroke",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 17
                  },
                  {
                      "weight": 1.2
                  }
              ]
          },
          {
              "featureType": "administrative.locality",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#c4c4c4"
                  }
              ]
          },
          {
              "featureType": "administrative.neighborhood",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#707070"
                  }
              ]
          },
          {
              "featureType": "landscape",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 20
                  }
              ]
          },
          {
              "featureType": "poi",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 21
                  },
                  {
                      "visibility": "on"
                  }
              ]
          },
          {
              "featureType": "poi.business",
              "elementType": "geometry",
              "stylers": [
                  {
                      "visibility": "on"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "geometry.fill",
              "stylers": [
                  {
                      "color": "#be2026"
                  },
                  {
                      "lightness": "0"
                  },
                  {
                      "visibility": "on"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "geometry.stroke",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "visibility": "off"
                  }
              ]
          },
          {
              "featureType": "road.highway",
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "visibility": "off"
                  },
                  {
                      "hue": "#ff000a"
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 18
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "geometry.fill",
              "stylers": [
                  {
                      "color": "#575757"
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#ffffff"
                  }
              ]
          },
          {
              "featureType": "road.arterial",
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "color": "#2c2c2c"
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 16
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "labels.text.fill",
              "stylers": [
                  {
                      "color": "#999999"
                  }
              ]
          },
          {
              "featureType": "road.local",
              "elementType": "labels.text.stroke",
              "stylers": [
                  {
                      "saturation": "-52"
                  }
              ]
          },
          {
              "featureType": "transit",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 19
                  }
              ]
          },
          {
              "featureType": "water",
              "elementType": "geometry",
              "stylers": [
                  {
                      "color": "#000000"
                  },
                  {
                      "lightness": 17
                  }
              ]
          }
      ]
    });

    
  }

  function codeAddress(){
    // 入力を取得
    let inputAddress = document.getElementById('address').value;

    // geocodingしたあとmapを移動
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['MAP_API_KEY']%>&callback=initMap" async defer></script>

app/views/events/_type_content.html.erb
  <div class="content active" id="all">
    <% @events.each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="vollayball">
    <% @events.where(type_id: 1).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="baseball">
    <% @events.where(type_id: 2).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="football">
    <% @events.where(type_id: 3).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="bowling">
    <% @events.where(type_id: 4).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="tennis">
    <% @events.where(type_id: 5).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="basketball">
    <% @events.where(type_id: 6).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="handball">
    <% @events.where(type_id: 7).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="badminton">
    <% @events.where(type_id: 8).each do |event| %>
      <% if event.finish_date > Time.zone.now %>
        <%= link_to event_path(event), class: "event-index__item" do %>
          <div class="text-center">
            <ul>
              <li><h2><%= event.event_name %></h2></li>
              <li class="introduction-padding"><%= event.introduction %></li>  
            </ul>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= render "type_select_script" %>

app/views/events/_type_select.html.erb
<div class="text-center">
  <div class="event-top">
    <div class="event-top__text">
      <h2>イベント一覧</h2>
    </div>
    <%# <div class="event-top__button">
      <button class="event-button btn btn-success">地域別に検索</button>
    </div>
  </div>
<div>
  <div class="map-area" id="map-area">
    <%= render "map" %>
    <%# <button class="btn btn-danger" id="close">閉じる</button>
  </div>
</div>  %>

<%# <script>
  $(function(){
    $(".event-button").click(function() {
      $(".map-area").fadeIn(1000);
    });

    $("#close").click(function() {
      $(".map-area").fadeOut(1000);
    });
  });
</script> %>

  <%#= form_tag events_path, method: :get, class: 'boards__searchForm' do %>
    <%#= select_tag :type_id, options_from_collection_for_select(Type.all, :id, :name, params[:type_id]),{prompt: 'タグで絞り込み検索', onchange: 'submit(this.form);'} %>
  <%# end %>
  <ul class="menu">
    <li>
      <%= link_to events_path, class: "event-type active", data: {id: "all"} do %>
        All
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 1), class: "event-type", data: {id: "vollayball"} do %>
        バレーボール
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 2), class: "event-type", data: {id: "baseball"} do %>
        野球
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 3), class: "event-type", data: {id: "football"} do %>
        フットサル
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 4), class: "event-type", data: {id: "bowling"} do %>
        ボウリング
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 5), class: "event-type", data: {id: "tennis"} do %>
        テニス
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 6), class: "event-type", data: {id: "basketball"} do %>
        バスケット
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 7), class: "event-type", data: {id: "handball"} do %>
        ハンドボール
      <% end %>
    </li>
    <li>
      <%= link_to events_path(type_id: 8), class: "event-type", data: {id: "badminton"} do %>
        バドミントン
      <% end %>
    </li>
  </ul>
</div>

app/views/events/_type_select_script.html.erb
<script>
  {
    const menuItems = document.querySelectorAll('.menu li a');
    const contents = document.querySelectorAll('.content');

    menuItems.forEach(clickedItem => {
      clickedItem.addEventListener('click', e => {
        e.preventDefault();

        menuItems.forEach(item => {
          item.classList.remove('active');
        });
        clickedItem.classList.add('active');

        contents.forEach(content => {
          content.classList.remove('active');
        });
        document.getElementById(clickedItem.dataset.id).classList.add('active');
      });
    });
  }
</script>

app/views/events/edit.html.erb
<% if @event.errors.any? %>

  <h2><%= @event.errors.count %>errors prohibited this  from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="event-new">
  <div class="bottom-color">新規イベント作成</div>
  <div class="event-new__form">
    <%= form_for @event do |f| %>
      <div class="event-new__form__label">
        <%= f.label :event_name, "イベント名" %>
        <%= f.text_field :event_name, autofocus: true, autocomplete: "event_name", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :type_id, "イベント種目" %>
        <%= f.select :type_id, Type.all.collect {|t| [t.name, t.id]}, {}, {class: "form-control"} %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :start_date, "開催日時" %>
        <%= f.datetime_field :start_date, autofocus: true, autocomplete: "開催日時", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :finish_date, "終了日時" %>
        <%= f.datetime_field :finish_date, autofocus: true, autocomplete: "終了日時", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :place_name, "開催場所名" %>
        <%= f.text_field :place_name, autofocus: true, autocomplete: "開催場所名", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :address, "住所" %>
        <%= f.text_field :address, autofocus: true, autocomplete: "住所", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :introduction, "イベント紹介文" %>
        <%= f.text_area :introduction, autofocus: true, autocomplete: "イベント紹介文", class: "form-control" %>
      </div>
      
      <%= f.submit "編集内容を保存する", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="event-index">
  
  <%= render "type_select" %>

  <%= render "type_content"%>

  <div class="event-host text-center">
    <%= link_to "新たにイベントを開催する", new_event_path, class: "btn btn-success"%>
  </div>
</div>

app/views/events/new.html.erb
<div class="event-new">
  <div class="bottom-color">新規イベント作成</div>
  <div class="event-new__form">
    <%= form_for @event do |f| %>
      <div class="event-new__form__label">
        <%= f.label :event_name, "イベント名" %>
        <%= f.text_field :event_name, autofocus: true, autocomplete: "event_name", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :type_id, "イベント種目" %>
        <%= f.select :type_id, Type.all.collect {|t| [t.name, t.id]}, {}, {class: "form-control"} %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :start_date, "開催日時" %>
        <%= f.datetime_field :start_date, autofocus: true, autocomplete: "開催日時", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :finish_date, "終了日時" %>
        <%= f.datetime_field :finish_date, autofocus: true, autocomplete: "終了日時", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :place_name, "開催場所名" %>
        <%= f.text_field :place_name, autofocus: true, autocomplete: "開催場所名", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :address, "住所" %>
        <%= f.text_field :address, autofocus: true, autocomplete: "住所", class: "form-control" %>
      </div>

      <div class="event-new__form__label">
        <%= f.label :introduction, "イベント紹介文" %>
        <%= f.text_area :introduction, autofocus: true, autocomplete: "イベント紹介文", class: "form-control" %>
      </div>

      <%= f.submit "編集内容を保存する", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-show">

  <%= render "event_show_top"%>

  <div class="row event-show-main">
    <div class="col-lg-7 col-md-12 col-sm-12 col-xs-12 event-show-main__item-introduction">
      <div class="panel panel-success participation-index">
        <div class="panel-heading participation-index__heading">
          <h3>紹介文</h3>
        </div>
        <div class="panel-body participation-index__body">
          <p><%= @event.introduction %></p>
        </div>
      </div>
    </div>
    
    <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12 event-show-main__item-participation">
      <div class="panel panel-success participation-index">
        <div class="panel-heading participation-index__heading">
          <h3>参加者</h3>
        </div>
        <div class="panel-body participation-index__body">
          <table>
            <% @participations.each do |participation| %>
            <tr class="text-center">
              <% if participation.user.image? %>
                <td width="200" height="100"><%= image_tag(User.find_by(id: participation.user).image.to_s, size: "100x100") unless User.find_by(id: participation.user).image.nil? %></td>
              <% else %>
                <td width="200" height="100"><%= image_tag("no_image.jpg", size: "100x100") %></td>
              <% end %>
              <td width="150" height="60"><%= link_to "#{participation.user.name}", user_path(participation.user_id) %></td>
              <td width="150" height="60"><%= "#{participation.user.age}歳" %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

  <%= render "event_comment"%>

</div>


<%= render 'mapstyle' %>