config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get '/home/about', to: 'home#about'
  get '/users/:id/following', to: 'users#following'
  get '/users/:id/followers', to: 'users#followers'
  get '/search', to: 'search#search'

  resources :notifications, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:edit, :update, :show] do
    member do
      get :following, :followers
    end
  end
  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :events, only: [:new, :index, :create, :edit, :update, :show] do
    resources :comments, only: [:create, :destroy]
    resources :teams, only: [:new, :index, :create, :edit, :update, :show], shallow: true
    resources :participations, shallow: true
    resources :games, only: [:new, :index, :create, :edit, :update, :show] do
      collection do
        get 'halfway'
        post 'halfway'
        get 'battles'
        post 'battles'
      end
    end
  end

  resources :locations, only: [:new, :index, :create, :edit, :update, :show]
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :event
  has_many :game_details, dependent: :destroy
  has_many :resolutes, dependent: :destroy

  validates :event_id, presence: true
  validates :win_id, presence: true
  validates :lose_id, presence: true
  validate :score_custom_validation

  def score_custom_validation
    errors.add(:win_score, "他チームと異なる値を入力して下さい") if win_score == lose_score
  end

  def self.game_index(event_id)
    self.where(event_id: event_id)
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.game_index(params[:event_id])
  end

  def new
    @event = Event.find(params[:event_id])
    @participation = Participation.new
    participations = Participation.participation_index(params[:event_id])
    @users = User.where(id: participations.map { |t| t.user_id })
  end

  def battles
    @event = Event.find(params[:event_id])
    @game = Game.new
    @number_of_teams = params[:number_of_teams].to_i
    @game_index = params[:game_index].to_i

    case @number_of_teams
    when 2
      @teams = []
      @teams.push(Team.team_detail(params[:event_id]).second)
      @teams.push(Team.team_detail(params[:event_id]).first)

      # 1チーム目のメンバーを取得
      team_detail1 = TeamDetail.where(team_id: @teams.first.id)
      participation_ids1 = []
      team_detail1.each do |team_detail1|
        participation_ids1.push(team_detail1.participation_id.to_i)
      end
      @member1 = Participation.where(id: participation_ids1)
      
      # 2チーム目のメンバーを取得
      team_detail2 = TeamDetail.where(team_id: @teams.second.id)
      participation_ids2 = []
      team_detail2.each do |team_detail2|
        participation_ids2.push(team_detail2.participation_id.to_i)
      end
      @member2 = Participation.where(id: participation_ids2)
      



    when 3
      @teams = []
      @teams.push(Team.team_detail(params[:event_id]).third)
      @teams.push(Team.team_detail(params[:event_id]).second)
      @teams.push(Team.team_detail(params[:event_id]).first)

      case @game_index
      when 1
      # 1チーム目のメンバーを取得
      team_detail1 = TeamDetail.where(team_id: @teams.first.id)
      participation_ids1 = []
      team_detail1.each do |team_detail1|
        participation_ids1.push(team_detail1.participation_id.to_i)
      end
      @member1 = Participation.where(id: participation_ids1)
      
      # 2チーム目のメンバーを取得
      team_detail2 = TeamDetail.where(team_id: @teams.second.id)
      participation_ids2 = []
      team_detail2.each do |team_detail2|
        participation_ids2.push(team_detail2.participation_id.to_i)
      end
      @member2 = Participation.where(id: participation_ids2)

      when 2
      # 1チーム目のメンバーを取得
      team_detail1 = TeamDetail.where(team_id: @teams.first.id)
      participation_ids1 = []
      team_detail1.each do |team_detail1|
        participation_ids1.push(team_detail1.participation_id.to_i)
      end
      @member1 = Participation.where(id: participation_ids1)
      
      # 2チーム目のメンバーを取得
      team_detail2 = TeamDetail.where(team_id: @teams.third.id)
      participation_ids2 = []
      team_detail2.each do |team_detail2|
        participation_ids2.push(team_detail2.participation_id.to_i)
      end
      @member2 = Participation.where(id: participation_ids2)
      
      when 3
      # 1チーム目のメンバーを取得
      team_detail1 = TeamDetail.where(team_id: @teams.second.id)
      participation_ids1 = []
      team_detail1.each do |team_detail1|
        participation_ids1.push(team_detail1.participation_id.to_i)
      end
      @member1 = Participation.where(id: participation_ids1)
      
      # 2チーム目のメンバーを取得
      team_detail2 = TeamDetail.where(team_id: @teams.third.id)
      participation_ids2 = []
      team_detail2.each do |team_detail2|
        participation_ids2.push(team_detail2.participation_id.to_i)
      end
      @member2 = Participation.where(id: participation_ids2)
      end
      
    end
  end

  def halfway
    @event = Event.find(params[:event_id])
    @game = Game.new
    @number_of_teams = params[:number_of_teams].to_i
    # チームを自動で作成
    @number_of_teams.times do
      Team.create(
        event_id: params[:event_id],
        name: Takarabako.open,
      )
    end

    case @number_of_teams
    when 2
      case params[:member_select]
      when  "all"
        participations = Participation.participation_index(params[:event_id])
        random_team = participations.shuffle
        team = random_team.to_a.in_groups(2, false) # チームを2つに分ける
        @member1 = team[0]                                              # team配列1つ目を1チーム目とする
        @member2 = team[1]                                              # team配列2つ目を2チーム目とする

        # チーム詳細を2チーム分作成する（どの会員がどのチームに属しているか分かるようにする）
        @member1.each do |member1| # 1つ目のチーム詳細作成
          TeamDetail.create!(
            team_id: Team.team_detail(params[:event_id]).second.id,
            participation_id: member1.id,
          )
        end

        @member2.each do |member2| # 2つ目のチーム詳細作成
          TeamDetail.create!(
            team_id: Team.team_detail(params[:event_id]).first.id,
            participation_id: member2.id,
          )
        end

        @team1 = Team.team_detail(params[:event_id]).second
        @team2 = Team.team_detail(params[:event_id]).first
        @event = Event.find(params[:event_id])
        @teams = []
        @teams.push(@team1)
        @teams.push(@team2)
      when  "select"
        # newページで取得した参加者の情報をParticipationのレコード上のidと合致させるための処理
        user_ids = []
        params[:participation_select][:user_id].each do |id|
          user_ids.push(id.to_i)
        end

        # newページで取得した参加者のidからチーム分けを行う
        participations = Participation.where(event_id: params[:event_id]).where(user_id: user_ids)
        random_team = participations.shuffle
        team = random_team.to_a.in_groups(2, false) # チームを2つに分ける
        @member1 = team[0]
        @member2 = team[1]

        # チーム詳細を2チーム分作成する（どの会員がどのチームに属しているか分かるようにする）
        @member1.each do |member1|                        # 1つ目のチーム詳細作成
          TeamDetail.create(
            team_id: Team.team_detail(params[:event_id]).second.id,
            participation_id: member1.id,
          )
        end

        @member2.each do |member2|                        # 2つ目のチーム詳細作成
          TeamDetail.create(
            team_id: Team.team_detail(params[:event_id]).first.id,
            participation_id: member2.id,
          )
        end

        @team1 = Team.team_detail(params[:event_id]).second
        @team2 = Team.team_detail(params[:event_id]).first
        @event = Event.find(params[:event_id])
        @teams = []
        @teams.push(@team1)
        @teams.push(@team2)

      when  "select_team"
        # newページで取得した参加者の情報をParticipationのレコード上のidと合致させるための処理
        user_ids1 = []
        params[:select_team1][:user_id].each do |id|
          user_ids1.push(id.to_i)
        end
        user_ids2 = []
        params[:select_team2][:user_id].each do |id|
          user_ids2.push(id.to_i)
        end

        @member1 = Participation.where(event_id: params[:event_id]).where(user_id: user_ids1)
        @member2 = Participation.where(event_id: params[:event_id]).where(user_id: user_ids2)

        # チーム詳細を2チーム分作成する（どの会員がどのチームに属しているか分かるようにする）
        @member1.each do |member1|                        # 1つ目のチーム詳細作成
          TeamDetail.create(
            team_id: Team.team_detail(params[:event_id]).second.id,
            participation_id: member1.id,
          )
        end

        @member2.each do |member2|                        # 2つ目のチーム詳細作成
          TeamDetail.create(
            team_id: Team.team_detail(params[:event_id]).first.id,
            participation_id: member2.id,
          )
        end

        @team1 = Team.team_detail(params[:event_id]).second
        @team2 = Team.team_detail(params[:event_id]).first
        @event = Event.find(params[:event_id])
        @teams = []
        @teams.push(@team1)
        @teams.push(@team2)

      end


    when 3
      case params[:member_select]
      when  "all"
        participations = Participation.participation_index(params[:event_id])
        random_team = participations.shuffle
        team = random_team.to_a.in_groups(3, false) # チームを3つに分ける
        @member1 = team[0]                                              # team配列1つ目を1チーム目とする
        @member2 = team[1]                                              # team配列2つ目を2チーム目とする
        @member3 = team[2]                                              # team配列3つ目を3チーム目とする

        # チーム詳細を2チーム分作成する（どの会員がどのチームに属しているか分かるようにする）
        @member1.each do |member1| # 1つ目のチーム詳細作成
          TeamDetail.create!(
            team_id: Team.team_detail(params[:event_id]).third.id,
            participation_id: member1.id,
          )
        end

        @member2.each do |member2| # 2つ目のチーム詳細作成
          TeamDetail.create!(
            team_id: Team.team_detail(params[:event_id]).second.id,
            participation_id: member2.id,
          )
        end

        @member3.each do |member3| # 3つ目のチーム詳細作成
          TeamDetail.create!(
            team_id: Team.team_detail(params[:event_id]).first.id,
            participation_id: member3.id,
          )
        end

        @team1 = Team.team_detail(params[:event_id]).third
        @team2 = Team.team_detail(params[:event_id]).second
        @team3 = Team.team_detail(params[:event_id]).first
        @event = Event.find(params[:event_id])
        @teams = []
        @teams.push(@team1)
        @teams.push(@team2)
        @teams.push(@team3)

      when  "select"
        # newページで取得した参加者の情報をParticipationのレコード上のidと合致させるための処理
        user_ids = []
        params[:participation_select][:user_id].each do |id|
          user_ids.push(id.to_i)
        end

        # newページで取得した参加者のidからチーム分けを行う
        participations = Participation.where(event_id: params[:event_id]).where(user_id: user_ids)
        random_team = participations.shuffle
        team = random_team.to_a.in_groups(3, false) # チームを2つに分ける
        @member1 = team[0]
        @member2 = team[1]
        @member3 = team[2]

        # チーム詳細を2チーム分作成する（どの会員がどのチームに属しているか分かるようにする）
        @member1.each do |member1|                        # 1つ目のチーム詳細作成
          TeamDetail.create(
            team_id: Team.team_detail(params[:event_id]).third.id,
            participation_id: member1.id,
          )
        end

        @member2.each do |member2|                        # 2つ目のチーム詳細作成
          TeamDetail.create(

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_divide_team.html.erb
<%#= form_for([@event ,@game]) do |f| %>
<%= form_tag event_games_path, method: :post do |f| %>
  <div class="game-halfway-container">
    <%#<div class="line"></div>%>
    <div class="game-halfway-container__team row">
      <div class="game-halfway-container__team__item text-left col-xs-6">
        <div class="team-item-left">
          <% @member1.each do |member1| %>
            <div class="team-item-left__user">
              <% if member1.user.image? %>
                <%= image_tag(User.find_by(id: member1.user_id).image.to_s, size: "80x80") unless User.find_by(id: member1.user_id).image.nil? %>
              <% else %>
                <%= image_tag("no_image.jpg", size: "80x80") %>
              <% end %>
              <div class="text-center"><%= member1.user.name %></div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="game-halfway-container__team__item col-xs-6">
        <div class="team-item-right text-right">
          <% @member2.each do |member2| %>
            <div class="team-item-right__user">
              <% if member2.user.image? %>
                <%= image_tag(User.find_by(id: member2.user_id).image.to_s, size: "80x80") unless User.find_by(id: member2.user_id).image.nil? %>
              <% else %>
                <%= image_tag("no_image.jpg", size: "80x80") %>
              <% end %>
              <div class="text-center"><%= member2.user.name %></div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="vs">
        <%= image_tag('vs.png', size: "100x100") %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 text-center">
      <% if @game_index == 3 %>
        <p>チーム1：<span><%= @teams[1].name %></span></p>
        <%= hidden_field_tag :team1, @teams[1].name %>
      <% else %>
        <p>チーム1：<span><%= @teams[0].name %></span></p>
        <%= hidden_field_tag :team1, @teams[0].name %>
      <% end %>
    </div>
    <div class="col-xs-6 text-center">
      <% if @game_index == 2 || @game_index == 3 %>
        <p>チーム2：<span><%= @teams[2].name %></span></p>
        <%= hidden_field_tag :team2, @teams[2].name %>
      <% else @game_index == 1 %>
        <p>チーム2：<span><%= @teams[1].name %></span></p>
        <%= hidden_field_tag :team2, @teams[1].name %>
      <% end %>
    </div>
  </div>
  <div class="score">
    <div class="score-width">
      <%= select_tag 'score1', options_for_select((1..300).to_a), class: "form-control" %>
    </div>
    <div class="score-width">
      <%= select_tag 'score2', options_for_select((1..300).to_a), class: "form-control" %>
    </div>
    <%#= select(:score2, (1..300).to_a, {include_blank: "点数"}, {class: "form-control", style: "width: 60px;"}) %>
  </div>

  <%= hidden_field_tag :number_of_teams, @number_of_teams %>
  <%= hidden_field_tag :game_index, @game_index %>

  <div class="text-center">
    <%= button_tag type: "submit", class: "btn btn-success btn-lg" do %>
      結果を記録する
    <% end %>
  </div>
<% end %>

app/views/games/battles.html.erb
<% if @game.errors.any? %>

  <h2><%= @game.errors.count %>errors prohibited this  from being saved:</h2>

  <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="game-halfway">
  <%= render "divide_team" %>
</div>

app/views/games/edit.html.erb
<div class="game-show">
  <%= form_for @game, url: event_game_path(event_id: @game.event_id, id: @game.id.to_i) do |f| %>
    <div class="panel panel-success game-show__panel">
      <div class="panel-heading game-show__panel__heading">
        <h2><%= "#{@game.id}試合目 結果編集" %></h2>
      </div>
      <div class="panel-body game-show__panel__body">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-6 team text-center">
            <div class="text-left">
              <div class="bottom-color"><%= @team_winer_name %>チーム</div>
            </div>
            <div>
              <% @member_winer.each do |member_winer| %>
              <div class="text-center">
                <div width="100" class="text-center">
                  <% if member_winer.image? %>
                    <%= image_tag(member_winer.image.to_s, size: "80x80") unless member_winer.image.nil? %>
                  <% else %>
                    <%= image_tag("no_image.jpg", size: "80x80") %>
                  <% end %>
                </div>
                <div>
                  <%= member_winer.name %>
                </div>
              </div>
              <% end %>
            </div>
            <hr>
            <div class="score text-center">
              <%= f.label :win_score, "点数" %>
              <%= f.number_field :win_score, autofocus: true, autocomplete: "win_score", class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-6 team text-center">
            <div class="text-left">
              <div class="bottom-color"><%= @team_loser_name %>チーム</div>
            </div>
            <div>
              <% @member_loser.each do |member_loser| %>
              <div>
                <div class="text-center">
                  <% if member_loser.image? %>
                    <%= image_tag(member_loser.image.to_s, size: "80x80") unless member_loser.image.nil? %>
                  <% else %>
                    <%= image_tag("no_image.jpg", size: "80x80") %>
                  <% end %>
                </div>
                <div>
                  <%= member_loser.name %>
                </div>
              </div>
              <% end %>
            </div>
            <hr>
            <div class="score text-center">
              <%= f.label :lose_score, "点数" %>
              <%= f.number_field :lose_score, autofocus: true, autocomplete: "lose_score", class: "form-control" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= f.submit "変更する", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/games/halfway.html.erb
<% if @number_of_teams == 3 %>
  <div class="text-center">
    <div class="game-list">
      <%= "#{@teams[0].name} VS #{@teams[1].name}" %><br>
      <%= link_to "試合をする", battles_event_games_path(event_id: params[:event_id], game_index: 1, number_of_teams: @number_of_teams), class: "btn btn-success" %><br>
    </div>
    <div class="game-list">
      <%= "#{@teams[0].name} VS #{@teams[2].name}" %><br>
      <%= link_to "試合をする", battles_event_games_path(event_id: params[:event_id], game_index: 2, number_of_teams: @number_of_teams), class: "btn btn-success" %><br>
    </div>
    <div class="game-list">
      <%= "#{@teams[1].name} VS #{@teams[2].name}" %><br>
      <%= link_to "試合をする", battles_event_games_path(event_id: params[:event_id], game_index: 3, number_of_teams: @number_of_teams), class: "btn btn-success" %><br>
    </div>
  </div>
<% elsif @number_of_teams == 2 %>
  <div class="text-center">
    <div class="game-list">
      <%= "#{@teams[0].name} VS #{@teams[1].name}" %><br>
      <%= link_to "試合をする", battles_event_games_path(event_id: params[:event_id], game_index: 4, number_of_teams: @number_of_teams), class: "btn btn-success" %><br>
    </div>
  </div>
<% end %>

<div class="text-center">
  <%= link_to "新たな試合を始める", new_event_game_path(event_id: params[:event_id]), class: "btn btn-success" %>
  <% if Game.find_by(event_id: params[:event_id]).present? %>
    <%= link_to "試合結果一覧を見る", event_games_path(event_id: params[:event_id]), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="game-index text-center">

      <div class="panel panel-success">
        <div class="panel-heading">
          <h2>試合結果一覧</h2>
        </div>
        <div class="panel-body game-index-panel__body">
          <table class="game-index__table">
            <% @games.each.with_index(1) do |game, i| %>
              <tr>
                <th class="index"><%= "#{i}試合目" %></th>
                <% if (game.win_id) < (game.lose_id) %>
                  <td class="win-lose-left">
                    <div class="winer">winer</div>
                  </td>
                  <td class="team-name"><%= Team.find_by(id: game.win_id).name %></td>
                  <td class="score"><%= game.win_score %></td>
                  <td>ー</td>
                  <td class="score"><%= game.lose_score %></td>
                  <td class="team-name"><%= Team.find_by(id: game.lose_id).name %></td>
                  <td></td>
                <% else %>
                  <td></td>
                  <td class="team-name"><%= Team.find_by(id: game.lose_id).name %></td>
                  <td class="score"><%= game.lose_score %></td>
                  <td>ー</td>
                  <td class="score"><%= game.win_score %></td>
                  <td class="team-name"><%= Team.find_by(id: game.win_id).name %></td>
                  <td class="win-lose-right">
                    <div class="winer">winer</div>
                  </td>
                <% end %>
                <td>
                  <%= link_to "詳細を見る", event_game_path(event_id: params[:event_id], id: game.id) %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
      <%= link_to "イベント詳細", event_path(id: params[:event_id]), class: "btn btn-lg btn-success" %>
</div>

app/views/games/new.html.erb
<div class="game-new">

  <%= form_tag halfway_event_games_path, method: :get do |f| %>
    <div class="game-new__container">
      <div class="panel panel-success game-new__container__panel">
        <div class="panel-heading">
          <h2>紅白戦新規作成</h2>
        </div>
        <div class="panel-body">

          <div class="row">
            <div class="col-lg-3">
              <div class="side-color">試合日</div>
            </div>
            <div class="col-lg-9">
              <%= @event.start_date.strftime('%Y年%m月%d日') %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-lg-3">
              <div class="side-color">チーム数</div>
            </div>
            <div class="col-lg-9">
              <div class="member_select">
                <%= label_tag :number_of_teams, "何チームに分けますか" %>
                <%= select_tag("number_of_teams", options_for_select(2..3), class: "form-control")%>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-lg-3">
              <div class="side-color">参加メンバー</div>
            </div>
            <div class="col-lg-9">
              <%= radio_button_tag :member_select, "all", checked: true %>
              <%= label_tag :member_select, "イベント参加メンバー全員"%>
            </div>
          </div>
          <div class="row">
          <br>
            <div class="col-lg-3"></div>
            <div class="col-lg-9">
              <%= radio_button_tag :member_select, "select" %>
              <%= label_tag :member_select, "参加メンバーを選択" %><br>
              <div class="member_select">
                <%= collection_select(:participation_select, :user_id, @users, :id, :name, {include_hidden: false}, {multiple: true, class: "form-control"}) %>
              </div>
              <br>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-9">
              <div class="row">
                <div class="col-lg-6 col-md-12">
                  <%= radio_button_tag :member_select, "select_team" %>
                  <%= label_tag :member_select, "チームを自分で決める"%><br>
                  <div class="team-select">
                    <%= label_tag :id, "チーム1" %>
                    <div class="member-select">
                      <%= collection_select(:select_team1, :user_id, @users, :id, :name, {include_hidden: false}, {multiple: true, class: "form-control"}) %>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 col-md-12">
                  <br>
                  <div class="team-select">
                    <%= label_tag :id, "チーム2" %>
                    <div class="member-select">
                      <%= collection_select(:select_team2, :user_id, @users, :id, :name, {include_hidden: false}, {multiple: true, class: "form-control"}) %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center" style="margin-top: 20px;">
            <p>※MacBookをお使いの方はshiftもしくはcommandを押しながら選択下さい。</p>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= button_tag type: "submit", class: "btn btn-success" do %>試合をする<% end %>
    </div>
  <% end %>
</div>
            

app/views/games/show.html.erb
<div class="game-show">
  <div class="panel panel-success game-show__panel">
    <div class="panel-heading game-show__panel__heading">
      <h2><%= "#{@game.id}試合目 試合結果" %></h2>
      <div class="game-edit">
        <%= link_to edit_event_game_path do %>
          <i class="fas fa-cog icon-orange"></i>
        <% end %>
      </div>
    </div>
    <div class="panel-body game-show__panel__body">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 team text-center">
          <div class="text-left">
            <div class="bottom-color"><%= @team_winer_name %>チーム</div>
          </div>
          <div>
            <% @member_winer.each do |member_winer| %>
              <div class="text-center">
                <div width="100" class="text-center">
                  <% if member_winer.image? %>
                    <%= image_tag(member_winer.image.to_s, size: "80x80") unless member_winer.image.nil? %>
                  <% else %>
                    <%= image_tag("no_image.jpg", size: "80x80") %>
                  <% end %>
                </div>
                <div>
                  <%= member_winer.name %>
                </div>
              </div>
            <% end %>
          </div>
          <hr>
          <div class="score">
            <%= "獲得点数：#{@win_score}" %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 team text-center">
          <div class="text-left">
            <div class="bottom-color"><%= @team_loser_name %>チーム</div>
          </div>
          <div>
            <% @member_loser.each do |member_loser| %>
              <div>
                <div class="text-center" width="100">
                  <% if member_loser.image? %>
                    <%= image_tag(member_loser.image.to_s, size: "80x80") unless member_loser.image.nil? %>
                  <% else %>
                    <%= image_tag("no_image.jpg", size: "80x80") %>
                  <% end %>
                </div>
                <div>
                  <%= member_loser.name %>
                </div>
              </div>
            <% end %>
          </div>
          <hr>
          <div class="score">
            <%= "獲得点数：#{@lose_score}" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center">
    <% if @game.event.finish_date > Time.zone.now %>
      <%= link_to "新たな試合を始める", new_event_game_path(event_id: params[:event_id]), class: "btn btn-success" %>
      <%= link_to "試合結果を一覧見る", event_games_path, class: "btn btn-success" %>
    <% else %>
      <%= link_to "試合結果を一覧見る", event_games_path, class: "btn btn-success" %>
    <% end %>
  </div>
</div>